---
# tasks file for webserver
- name: Install Apache
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd

- name: Created index
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart httpd
